---

# https://unsloth.ai/docs/basics/claude-codex

services:

  agent-glm-4.7.air:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda12-b7801
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8002:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/llama.cpp
    command: >
      --hf-repo DavidAU/GLM-4.7-Flash-Uncensored-Heretic-NEO-CODE-Imatrix-MAX-GGUF:Q4_K_M
      --host 0.0.0.0
      --port 8000
      --parallel 2
      --ctx-size 131072
      --batch-size 2048
      --n-predict 16384
      --ubatch-size 512
      --n-gpu-layers 999
      --prio 3
      --cont-batching
      --temp 1.0 
      --top-k 50
      --top-p 0.95
      --min-p 0.01
      --dry-multiplier 0.0
      --flash-attn off
      --jinja
      --tensor-split 2,1 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2','3']
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  open-webui:
    driver: local

networks:
  ai-network:
    driver: bridge
