---

services:

  # Nvidia Nemotron 3 Nano
  iquest-coder-instruct:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda-b7493
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8002:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/llama.cpp
    command: >
      --host 0.0.0.0
      --port 8000
      --hf-repo cturan/IQuest-Coder-V1-40B-Instruct-GGUF:Q4_K_M
      --alias iquest-coder-instruct
      --gpu-layers -1
      --tensor-split 1,2
      --split-mode layer
      --ctx-size 20000 
      --temp 0.8
      --top-k 40
      --top-p 0.9
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2','3']
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  open-webui:
    driver: local

networks:
  ai-network:
    driver: bridge

