---

# https://unsloth.ai/docs/basics/claude-codex

services:

  agent-glm-4.7.air:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8002:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/llama.cpp
    command: >
      --hf-repo unsloth/GLM-4.7-Flash-GGUF:UD-Q4_K_XL
      --host 0.0.0.0
      --port 8000
      --fit on
      --temp 1.0
      --top-p 0.95
      --min-p 0.01
      --port 8000
      --jinja
      --kv-unified
      --cache-type-k q8_0
      --cache-type-v q8_0
      --flash-attn on
      --batch-size 4096
      --ubatch-size 1024
      --ctx-size 131072
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  open-webui:
    driver: local

networks:
  ai-network:
    driver: bridge