---

# Doc: https://unsloth.ai/docs/models/glm-4.7
# Model: https://huggingface.co/unsloth/GLM-4.7-REAP-218B-A32B-GGUF

services:

  step-3.5-flash:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda12-b7981
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8002:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/llama.cpp
    command: >
      --host 0.0.0.0
      --port 8000
      -v
      --hf-repo stepfun-ai/Step-3.5-Flash-GGUF-Q4_K_S:Q4_K_S
      --alias coding-agent
      --ctx-size 32768 
      --n-predict 16384 
      --batch-size 2048
      --ubatch-size 2048
      --cont-batching
      --parallel 1
      --cache-type-k q8_0
      --cache-type-v q8_0
      --flash-attn on
      --temp 1.0
      --jinja
      --fit on
      --threads 40
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','1','2','3']
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  open-webui:
    driver: local

networks:
  ai-network:
    driver: bridge

