---

services:

  devstral-2-instruct:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda-b7623
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8002:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/llama.cpp
    command: >
      --host 0.0.0.0
      --port 8000
      --hf-repo unsloth/Devstral-2-123B-Instruct-2512-GGUF:IQ4_XS
      --alias coding-agent 
      --gpu-layers -1
      --tensor-split 1,1,1
      --split-mode layer
      --ctx-size 120000
      --temp 0.15
      --top-k 40
      --top-p 0.9
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1','2','3']
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  open-webui:
    driver: local

networks:
  ai-network:
    driver: bridge

