---

services:

  agent-glm-4.7.air:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8002:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/llama.cpp
    command: >
      --host 0.0.0.0
      --port 8000
      --hf-repo unsloth/GLM-4.7-Flash-GGUF:Q5_K_M
      --alias coding-agent
      --threads -1
      --parallel 2
      --flash-attn off
      --ctx-size 32000
      --n-gpu-layers 999
      --prio 3
      --jinja
      --cont-batching
      --temp 0.9
      --top-k 50
      --top-p 0.95
      --min-p 0.01
      --dry-multiplier 0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2','3']
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  open-webui:
    driver: local

networks:
  ai-network:
    driver: bridge

