name: Autocomplete confgiguration
version: 1.0.0

models:

  - name: Codellama Python 7B ( fast )
    provider: openai
    model: codellama-python-7b
    apiBase: http://192.168.4.178:8000
    roles:
      - autocomplete
    requestOptions:
      extraBodyProperties:
        think: false
    autocompleteOptions:
      disable: false
      maxPromptTokens: 1024
      debounceDelay: 250
      modelTimeout: 150
      maxSuffixPercentage: 0.2
      prefixPercentage: 0.3
      onlyMyCode: true

  - name: Qwen Coder 7B ( fast )
    provider: openai
    model: qwen2.5-coder-7b-instruct
    apiBase: http://192.168.4.178:8000
    roles:
      - autocomplete
    requestOptions:
      extraBodyProperties:
        think: false
    autocompleteOptions:
      disable: false
      maxPromptTokens: 1024
      debounceDelay: 250
      modelTimeout: 150
      maxSuffixPercentage: 0.2
      prefixPercentage: 0.3
      onlyMyCode: true

  - name: Qwen Coder 32B ( chat )
    provider: openai
    model: qwen3-vl-32b-thinking
    apiBase: http://192.168.4.178:8001
    roles:
      - chat
    requestOptions:
      extraBodyProperties:
        think: true
