name: Autocomplete confgiguration
version: 1.0.0

models:

  - name: Qwen Coder 7B ( fast )
    provider: openai
    model: qwen-coder
    apiBase: http://192.168.4.178:8000
    roles:
      - autocomplete

  - name: Qwen Coder 32B ( chat )
    provider: openai
    model: qwen3-vl-32b-thinking
    apiBase: http://192.168.4.178:8001
    roles:
      - chat

