name: Autocomplete
version: 1.0.0

models:

  - name: Qwen Coder 7B ( fast )
    provider: openai
    model: coding-completion
    apiBase: http://127.0.0.1:8000
    requestOptions:
      extraBodyProperties:
        think: false
    roles:
      - autocomplete
    autocompleteOptions:
      disable: false
      maxPromptTokens: 1024
      debounceDelay: 250
      modelTimeout: 150
      maxSuffixPercentage: 0.2
      prefixPercentage: 0.3
      onlyMyCode: true

  - name: Qwen thinking 32B ( chat )
    provider: openai
    model: coding-agent
    apiBase: http://127.0.0.1:8002
    roles:
      - chat

