---

# Models
# hf download --local-dir /home/luismi/ai/tools/llamacpp/models lmstudio-community/Qwen3-Coder-30B-A3B-Instruct-GGUF Qwen3-Coder-30B-A3B-Instruct-Q8_0.gguf
# hf download --local-dir . lmstudio-community/Olmo-3-32B-Think-GGUF Olmo-3-32B-Think-Q8_0.gguf
# arcee/Trinity-Mini-Q4_K_M.gguf
# microsoft/phi-4-gguf phi-4-Q4_K.gguf

services:
  completion-qwen-coder-7b:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/llama.cpp
    command: >
      --host 0.0.0.0
      --port 8000
      --hf-repo Qwen/Qwen2.5-Coder-7B-Instruct-GGUF
      --hf-file qwen2.5-coder-7b-instruct-q4_k_m.gguf
      --alias qwen2.5-coder-7b-instruct
      -c 10000
      --gpu-layers -1
      --tensor-split 1
      --split-mode layer
      --temp 0.8
      --top-k 40
      --top-p 0.9
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  open-webui:
    driver: local

networks:
  ai-network:
    driver: bridge

