---

services:

  # Nvidia Nemotron 3 Nano 
  thinking-nemotron-3-nano-30b:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda-b7416
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8002:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/llama.cpp
    command: >
      --host 0.0.0.0
      --port 8000
      --hf-repo unsloth/Nemotron-3-Nano-30B-A3B-GGUF:Q4_K_M
      --alias nvidia-nemotron-3-nano-30b
      --gpu-layers -1
      --tensor-split 1,1
      --split-mode layer
      --ctx-size 120000
      --temp 0.8
      --top-k 40
      --top-p 0.9
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','1']
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  open-webui:
    driver: local

networks:
  ai-network:
    driver: bridge

