global:
  resolve_timeout: 5m
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "alertmanager@example.com"
  smtp_auth_username: "alertmanager@example.com"
  smtp_auth_password: "YOUR_SMTP_PASSWORD_OR_APP_PASSWORD"
  smtp_require_tls: true

route:
  receiver: "default-notifications"
  group_by: ["alertname", "cluster", "service"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receivers:
    - name: "default-notifications"
      email_configs:
        - to: "you@example.com"
          send_resolve_notifications: true
