---

# Models
# hf download --local-dir /home/luismi/ai/tools/llamacpp/models lmstudio-community/Qwen3-Coder-30B-A3B-Instruct-GGUF Qwen3-Coder-30B-A3B-Instruct-Q8_0.gguf
# hf download --local-dir . lmstudio-community/Olmo-3-32B-Think-GGUF Olmo-3-32B-Think-Q8_0.gguf
# arcee/Trinity-Mini-Q4_K_M.gguf
# microsoft/phi-4-gguf phi-4-Q4_K.gguf

services:

  # ComfyUI GPU
  # Nodes:
  # - https://github.com/Comfy-Org/ComfyUI-Manager
  # - https://github.com/rgthree/rgthree-comfy
  # - https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
  # - https://github.com/Lightricks/ComfyUI-LTXVideo
  # - https://github.com/numz/ComfyUI-SeedVR2_VideoUpscaler
  # - https://github.com/1038lab/ComfyUI-QwenVL
  # - https://github.com/Fannovel16/comfyui_controlnet_aux
  # - https://github.com/PGCRT/CRT-Nodes
  # - https://github.com/dreamfast/ComfyUI-LTX2-MultiGPU
  # - https://github.com/BennyDaBall930/ComfyUI-Z-Engineer
  # - https://github.com/jtydhr88/ComfyUI-qwenmultiangle
  # - https://github.com/ltdrdata/ComfyUI-Impact-Pack
  # - https://github.com/yolain/ComfyUI-Easy-Use
  # - https://github.com/kijai/ComfyUI-KJNodes
  # - https://github.com/Fannovel16/ComfyUI-Frame-Interpolation
  comfy-gpu:
    image: yanwk/comfyui-boot:cu126-slim-20260112
    #build:
    #  context: comfy/ComfyUI-Docker/cu126-slim
    ports:
      - "8188:8188"
    security_opt:
      - "label=type:nvidia_container_t"
    volumes:
      - ${HOME}/comfy/ComfyUI/models:/root/ComfyUI/models
      - ${HOME}/comfy/ComfyUI/user/default/workflows:/root/ComfyUI/user/default/workflows
    environment:
      CLI_ARGS: "--disable-xformers"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','1','2','3']
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - ai

  # ComfyUI  CPU
  comfy-cpu:
    build:
      context: comfy/ComfyUI-Docker/cu128-slim
    ports:
      - "8189:8188"
    volumes:
      - ${HOME}/comfy/ComfyUI/models:/root/ComfyUI/models
      - ${HOME}/comfy/ComfyUI/user/default/workflows:/root/ComfyUI/user/default/workflows
    environment:
      CLI_ARGS: "--disable-xformers --novram"
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - ai 

  # Opencode agent
  # Models:
  # - unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q5_K_M
  agent:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8002:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/llama.cpp
    command: >
      --host 0.0.0.0
      --port 8000
      --hf-repo unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF:Q5_K_M
      --alias coding-agent
      --jinja
      --gpu-layers -1
      --tensor-split 1,1
      --split-mode layer
      --ctx-size 131072
      --fit on
      --temp 0.7
      --top-k 20
      --top-p 0.8
      --repeat-penalty 1.05
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1','2']
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - ai

  # Code completion
  completion:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/llama.cpp
    command: >
      --host 0.0.0.0
      --port 8000
      --hf-repo Qwen/Qwen2.5-Coder-7B-Instruct-GGUF
      --hf-file qwen2.5-coder-7b-instruct-q4_k_m.gguf
      --alias coding-completion 
      --ctx-size 10000
      --gpu-layers -1
      --tensor-split 1
      --split-mode layer
      --temp 0.8
      --top-k 40
      --top-p 0.9
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - ai

networks:
  ai:
    driver: bridge

