---

model: openbmb/MiniCPM-SALA
kv-cache-dtype: fp8
calculate-kv-scales: True
gpu-memory_utilization: 0.65
max-num_batched_tokens: 8192
max-num_seqs: 256
max-model_len: 8192
cpu-offload_gb: 0
tensor-parallel_size: 1
pipeline-parallel_size: 1
trust_remote_code: True
